### ISSUE TITLE
Incorrect unsafe implementation (possibly related with issue #1)

### ISSUE THREAD

**Issue by curioustorvald** [richardstartin/xxhash-benchmark#2]
To retrieve correct data from an array using Unsafe, you need to add the array base offset to the objects' own offset, producing code similar to this:
```
protected int getInt(byte[] array, int offset) {
    return UnsafeWrapper.getInt(array, offset + UNSAFE.arrayBaseOffset(array)); // notice the additional 'UNSAFE.arrayBaseOffset'
}
```

I'm leaving an issue here rather than a pull request as I'm not in a situation to run a test, thanks.

**Comment by richardstartin** [comment]
The usage is correct. The array base offset is added in `UnsafeWrapper` ([here](https://github.com/richardstartin/xxhash-benchmark/blob/master/src/main/java/uk/co/openkappa/xxhash/UnsafeWrapper.java#L31)).
